servers:
  - url: https://api.ssoready.com

tags: {}

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      x-fern-bearer:
        name: apiKey
        env: SSOREADY_API_KEY

paths:
  /v1/saml/redeem:
    post:
      tags:
        - saml
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: redeemSAMLAccessCode
      x-fern-examples:
        - request:
            samlAccessCode: saml_access_code_...
          response:
            body:
              email: john.doe@acme.com
              organizationId: org_7cu5hsy9vrbi5d2k1qvbh19lj
              organizationExternalId: my_custom_external_id

  /v1/saml/redirect:
    post:
      tags:
        - saml
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: getSAMLRedirectUrl
      x-fern-examples:
        - request:
            organizationExternalId: my_custom_external_id
          response:
            body:
              redirectUrl: https://your.redirect.url

  /v1/scim/users:
    get:
      tags:
        - scim
      x-fern-sdk-group-name: scim
      x-fern-sdk-method-name: listSCIMUsers
      x-fern-examples:
        - request:
            organizationExternalId: my_custom_external_id
          response:
            body:
              scimUsers:
                - id: scim_user_...
                  email: john.doe@acme.com
                  deleted: false
                  attributes:
                    displayName: John Doe
                    preferredLanguage: en_US
                    key: value
                - id: scim_user_...
                  email: jane.doe@acme.com
                  deleted: true
                  attributes:
                    displayName: Jane Doe
                    preferredLanguage: fr_FR
                    key: value
              nextPageToken: "..."

  /v1/scim/users/{id}:
    get:
      tags:
        - scim
      x-fern-sdk-group-name: scim
      x-fern-sdk-method-name: getSCIMUser
      x-fern-examples:
        - request:
            id: scim_user_...
          response:
            body:
              scimUser:
                id: scim_user_...
                email: john.doe@acme.com
                deleted: false
                attributes:
                  displayName: John Doe
                  preferredLanguage: en_US
                  key: value

  /v1/scim/groups:
    get:
      tags:
        - scim
      x-fern-sdk-group-name: scim
      x-fern-sdk-method-name: listSCIMGroups
      x-fern-examples:
        - request:
            organizationExternalId: my_custom_external_id
          response:
            body:
              scimGroups:
                - id: scim_group_...
                  displayName: Engineering
                  deleted: false
                  attributes:
                    key: value
                - id: scim_group_...
                  displayName: Marketing
                  deleted: true
                  attributes:
                    key: value
              nextPageToken: "..."

  /v1/scim/groups/{id}:
    get:
      tags:
        - scim
      x-fern-sdk-group-name: scim
      x-fern-sdk-method-name: getSCIMGroup
      x-fern-examples:
        - request:
            id: scim_group_...
          response:
            body:
              scimGroup:
                id: scim_group_...
                displayName: Engineering
                deleted: false
                attributes:
                  key: value
